// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnuJ4iWgnqVH_6hqUG2iHCr0_XroP20Rw',
    appId: '1:645853072320:web:74469bcbdb7b6971d01625',
    messagingSenderId: '645853072320',
    projectId: 'try-space-9fc58',
    authDomain: 'try-space-9fc58.firebaseapp.com',
    storageBucket: 'try-space-9fc58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgTp4oxS1SLU4AbpIZaCFQLShTMl3Yaao',
    appId: '1:722802110473:android:dd86c35d5f1573664288d8',
    messagingSenderId: '722802110473',
    projectId: 'try-space-b395f',
    storageBucket: 'try-space-b395f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn-mbrl1bH-ekVFBc3b8nDwwUc0AQ_0sY',
    appId: '1:722802110473:ios:088bcf7b879f01574288d8',
    messagingSenderId: '722802110473',
    projectId: 'try-space-b395f',
    storageBucket: 'try-space-b395f.firebasestorage.app',
    iosClientId: '722802110473-s1h1q3hdejn28cs9pekgpbv4b2vd7a9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.trySpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5ZtMTccLi_rHVPnwTtiBwE5ESXJrIpUw',
    appId: '1:645853072320:ios:1d3350eaf6f5c994d01625',
    messagingSenderId: '645853072320',
    projectId: 'try-space-9fc58',
    storageBucket: 'try-space-9fc58.firebasestorage.app',
    iosBundleId: 'com.example.trySpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnuJ4iWgnqVH_6hqUG2iHCr0_XroP20Rw',
    appId: '1:645853072320:web:78ffb1569ca9d043d01625',
    messagingSenderId: '645853072320',
    projectId: 'try-space-9fc58',
    authDomain: 'try-space-9fc58.firebaseapp.com',
    storageBucket: 'try-space-9fc58.firebasestorage.app',
  );
}